<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Forms.DX" Version="3.2.1" />
    <PackageReference Include="NLua" Version="1.7.9" />
    <PackageReference Include="Tommy" Version="3.1.2" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
  

  <ItemGroup>
    <ProjectReference Include="..\Engine.Content\Engine.Content.csproj" />
    <ProjectReference Include="..\Engine\Engine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Form1.ProjectExplorer.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Form1.SceneHierarchy.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\Fallbacks\" />
    <Folder Include="Content\Scenes\" />
    <Folder Include="Content\Shaders\" />
    <Folder Include="Content\System\" />
    <Folder Include="Content\Templates\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Templates\.cs\Component.tmpl" />
    <None Include="Templates\.cs\DataComponent.tmpl" />
    <None Include="Templates\.cs\Manager.tmpl" />
    <None Include="Templates\.cs\Script.tmpl" />
    <None Include="Templates\.cs\SystemComponent.tmpl" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Content\Textures\missing texture.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>